### ISSUE TITLE
 Support for web api

### ISSUE THREAD

**Issue by JusticeN** [zakgof/actr#13]
I really appreciate your idea of pojo classes. It makes it easier to integrate with existing applications. 

It is really interesting to have an actor system that can communicate with the external world using standard protocol.

Did you already thing of building module for
- rest server (spark/jetty integration for example)
- graphql
- database persistence actors(redis, sql, mongo, ...)

And example to show how it could be used. What about creating predefined actor/connector to help better understand the power of actr. 
Like:
- PersistenceRedisActr(redis connector with some fonctions),
- PersistenceHibernateActr(works with hibernate objects)
- RestApiActr(handling http api request)
- GraphqlApiActr
- WebsocketActr
- EmailActr
- ...

Each of them with own ExecutorServive and a parameter to increase the number of threads

**Comment by zakgof** [comment]
Integrations with other frameworks can be implemented as separate projects, keeping `actr` itself as a general-purpose minimalistic lib. Currently, there are no plans to work on integrations. If someone starts such a project, that would be great.

**Comment by JusticeN** [comment]
ok i understand
