### ISSUE TITLE
how can i test it. mvn could not find the jar

### ISSUE THREAD

**Issue by JusticeN** [zakgof/actr#14]
after adding this dependency to my mvn project

```
<dependency>
            <groupId>com.github.zakgof</groupId>
            <artifactId>actr</artifactId>
            <version>0.4.0</version>
</dependency>
```

 i get thie error.

Could not find artifact com.github.zakgof:actr:pom:0.4.0 in central (https://repo.maven.apache.org/maven2)

does anyone has an ideas why. it seems like it is no more awailaible in maven repo

**Comment by zakgof** [comment]
`actr` is hosted on `jcenter`, just add it to repositories:

````
<repositories>
    <repository>
        <id>jcenter</id>
        <name>jcenter</name>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>`

**Comment by JusticeN** [comment]
thank it works now
